[package]
name = "pixoo-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divoom = "0.1.42"
eframe = "0.22.0"
env_logger = "0.10.0"
flowync = "5.1.0"
tokio = "1.32.0"
